# SakuraGroup Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/SakuraServer/SakuraGroup

#==================#
#   Basic Config   #
#==================#
Groups:
  - Citizen
  - Builder
  - Engineer
  - Designer

Time: 1
Measure: MINUTE

#==================#
#   Vault Config   #
#==================#
# Hook to Vault for economy integration
UseVault: false
# Costs
Cost:
  action: 500

#==================#
#   MySQL Config   #
#==================#
MySQL:
  Server:
    Address: localhost
    Port: 3306
  Database:
    Name: DatabaseName
    User_Name: UserName
    User_Password: UserPassword
    TablePrefix: sg_

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1