# SakuraGroup Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/SakuraServer/SakuraGroup

#==================#
#   Basic Config   #
#==================#
DefaultGroup: Citizen
Groups:
  Builder:
    Cost: 5000
    KeepCost: 3000
    ColorTag: "&b"
    Limit: 10
  Engineer:
    Cost: 5000
    KeepCost: 3000
    ColorTag: "&6"
    Limit: 10
  Designer:
    Cost: 5000
    KeepCost: 3000
    ColorTag: "&c"
    Limit: 10

Time: 2
Measure: WEEK

# ExpiredCheckInterval (Hour)
ExpiredCheckInterval: 3

#==================#
#   Vault Config   #
#==================#
# Hook to Vault for economy integration
UseVault: false

#==================#
#   MySQL Config   #
#==================#
MySQL:
  Server:
    Address: localhost
    Port: 3306
  Database:
    Name: DatabaseName
    User_Name: UserName
    User_Password: UserPassword
    TablePrefix: sg_

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 1.0